
services:
  api: &api
    container_name: demo-api
    build: .
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/health').raise_for_status()" ]
      interval: 5s
      retries: 10
      start_period: 1s
      timeout: 5s

  test:
      <<: *api
      container_name: demo-api-test
      profiles: ["test"]
      command: poetry run task ci
