# This workflow will install Python dependencies, run lint checks, and tests with Python 3.12
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: app-demo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Set up Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install --with dev

#    - name: Lint
#      run: |
#        poetry run task lint

    - name: Check Docker and Docker Compose versions
      run: |
        docker --version
        docker compose version

    - name: Build and test using Docker Compose
      run: |
        docker compose build test
        docker compose run --rm test
        docker compose down --remove-orphans --volumes 
